In [9]:
import numpy as np
import time
#understanding the difference in implementing a vectorized and non vectorized approach 
#we want to use a vectorized approach when dealing with large amounts of data so that we can write much more efficient code.

a=np.random.rand(1000000)
b=np.random.rand(1000000)

tic=time.time()
c=np.dot(a,b)
toc=time.time()
print('vecorized approach '+ str(1000*(toc-tic)) +"ms")
print(c)

c=0
tic=time.time()
for i in range(1000000):
    c+=a[i]*b[i]
toc=time.time()
print(c)    
print('For loop approach '+ str(1000*(toc-tic))+"ms")#we can see that the vectorized approach is much faster as compared to the non vectorized approach

vecorized approach 2.000093460083008ms
249775.14515557615
249775.14515557
For loop approach 669.0001487731934ms


In [10]:
#tips while working with numpy arrays/vectors in python

a=np.random.randn(5)
print(a)

[-0.07699907 -0.48782495  1.98033074  1.98452389 -0.67104431]


In [11]:
print(a.shape)#this is known as a first rank array in python this should be avoided as it doest exactly work how we expect it to work

(5,)


In [12]:
print(a.T)#Transpose looks exactly like a

[-0.07699907 -0.48782495  1.98033074  1.98452389 -0.67104431]


In [13]:
print(np.dot(a,a.T))#we should get a matrix in this case

8.554247399993068


In [15]:
#to solve this problem
b=np.random.randn(5,1)
print(b)
print(b.shape)

[[ 1.06733358]
 [ 0.31929724]
 [ 2.18747661]
 [-0.00534127]
 [ 0.71585721]]
(5, 1)


In [16]:
print(b.T)#see the two [[ ]]

[[ 1.06733358  0.31929724  2.18747661 -0.00534127  0.71585721]]


In [18]:
print(np.dot(b,b.T))

[[ 1.13920098e+00  3.40796671e-01  2.33476725e+00 -5.70091466e-03
   7.64058440e-01]
 [ 3.40796671e-01  1.01950730e-01  6.98455253e-01 -1.70545213e-03
   2.28571233e-01]
 [ 2.33476725e+00  6.98455253e-01  4.78505394e+00 -1.16838987e-02
   1.56592090e+00]
 [-5.70091466e-03 -1.70545213e-03 -1.16838987e-02  2.85291433e-05
  -3.82358517e-03]
 [ 7.64058440e-01  2.28571233e-01  1.56592090e+00 -3.82358517e-03
   5.12451544e-01]]


In [20]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
c

array([[ 1.13882245, -0.08741608,  1.05394537],
       [ 0.15522748, -0.39434808, -1.72387095],
       [ 0.08267402, -0.2043395 , -0.15430972]])